import type { Db } from 'mongodb';
import { COLLECTIONS } from '../collections.js';
import type { Migration } from './types.js';

/**
 * Stage 7: contacts, submission events, consent evidence, and abuse evidence
 * (blueprint 9.2).
 *
 * Append-only, per the rule in runner.ts: 001-005 are untouched.
 *
 * The index list follows what blueprint 9.2 states for each record, plus the
 * TTLs blueprint 9.5 sets for the two evidence collections. Where 9.2 names a
 * dimension the inbox will filter on (domain, page, geo) the index is created
 * now rather than in Stage 8, because adding it later to a populated collection
 * is the expensive version of the same decision.
 */
export const migration006Submissions: Migration = {
  id: '006_submissions',
  description: 'Contact, submission, consent, and abuse collections with their indexes',

  async up(db: Db): Promise<void> {
    await db.collection(COLLECTIONS.contacts).createIndexes([
      /**
       * Blueprint 9.2: "Unique workspace + normalized email for active records".
       *
       * Partial on the ACTIVE state, so a soft-deleted contact does not block a
       * later one with the same address - the same shape as the user and
       * workspace uniqueness rules from Stage 2.
       */
      {
        key: { workspaceId: 1, normalizedEmail: 1 },
        name: 'uniq_active_workspace_email',
        unique: true,
        partialFilterExpression: { recordStatus: 'active' },
      },

      // The inbox's default ordering and its filters (blueprint 4.7).
      { key: { workspaceId: 1, lastSubmissionAt: -1 }, name: 'workspace_last_submission' },
      { key: { workspaceId: 1, status: 1, lastSubmissionAt: -1 }, name: 'workspace_status_date' },
      { key: { workspaceId: 1, assigneeUserId: 1 }, name: 'workspace_assignee' },
      { key: { workspaceId: 1, tags: 1 }, name: 'workspace_tags' },
      // The 30-day contact-trash sweep (blueprint 9.5).
      { key: { recordStatus: 1, purgeAfter: 1 }, name: 'record_status_purge_after' },
    ]);

    await db.collection(COLLECTIONS.submissionEvents).createIndexes([
      // Blueprint 9.2: workspace/contact/date; widget/date; domain/page/geo.
      { key: { workspaceId: 1, contactId: 1, submittedAt: -1 }, name: 'workspace_contact_date' },
      { key: { workspaceId: 1, widgetId: 1, submittedAt: -1 }, name: 'workspace_widget_date' },
      {
        key: { workspaceId: 1, 'source.domain': 1, submittedAt: -1 },
        name: 'workspace_domain_date',
      },
      { key: { workspaceId: 1, 'geo.countryCode': 1 }, name: 'workspace_country' },

      /**
       * Idempotency, enforced by the database rather than only by Redis.
       *
       * Redis holds the 24-hour replay answer, but Redis is a cache that can be
       * flushed. This unique index is what makes "creates no duplicate event"
       * true even then, and it is scoped per workspace because the key is
       * generated by a widget, not by us.
       */
      {
        key: { workspaceId: 1, idempotencyKey: 1 },
        name: 'uniq_workspace_idempotency_key',
        unique: true,
      },
    ]);

    await db
      .collection(COLLECTIONS.consentEvents)
      .createIndexes([
        { key: { workspaceId: 1, contactId: 1, occurredAt: -1 }, name: 'workspace_contact_date' },
      ]);

    await db.collection(COLLECTIONS.abuseEvents).createIndexes([
      // Blueprint 9.2: workspace/widget/type/date.
      {
        key: { workspaceId: 1, widgetId: 1, type: 1, occurredAt: -1 },
        name: 'workspace_widget_type_date',
      },
      /**
       * Abuse evidence is aggregate evidence, not a record to keep forever.
       * 90 days matches the raw-interaction-event retention in blueprint 9.5;
       * a TTL index means the cleanup needs no sweep job to be correct.
       */
      { key: { occurredAt: 1 }, name: 'ttl_occurred_at', expireAfterSeconds: 90 * 24 * 60 * 60 },
    ]);
  },
};
